/// Number data and the builders that make numeric sequences.
///
/// The short, fixed lists are written out one entry per line, the same way the
/// letter data is, so they can be read and edited directly.
///
/// The long runs are *not* typed out. Counting to 100 is generated by
/// [NumberSequences.range] rather than written as a hundred lines, for three
/// reasons: the brief asks for the length to be configurable (1–10, 1–20,
/// 1–50, 1–100) and a generator is the only way to serve all four from one
/// definition; a typed list of a hundred entries is a place for a typo to hide
/// where no reviewer would find it; and skip-counting, countdowns and times
/// tables all fall out of the same few lines below.
abstract final class NumberSequences {
  /// The ten digits, written out.
  static const List<String> digits = <String>[
    '0',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
  ];

  /// One to ten, the first counting sequence a child meets.
  static const List<String> oneToTen = <String>[
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
  ];

  /// English names of [oneToTen], for a future spoken-number mode.
  static const List<String> oneToTenSpoken = <String>[
    'one',
    'two',
    'three',
    'four',
    'five',
    'six',
    'seven',
    'eight',
    'nine',
    'ten',
  ];

  /// Amharic names of [oneToTen], for the same future mode.
  static const List<String> oneToTenAmharic = <String>[
    'አንድ', // and
    'ሁለት', // hulät
    'ሶስት', // sost
    'አራት', // arat
    'አምስት', // amməst
    'ስድስት', // sədəst
    'ሰባት', // säbat
    'ስምንት', // səmmənt
    'ዘጠኝ', // zäṭäñ
    'አስር', // asər
  ];

  // --- Builders -----------------------------------------------------------

  /// Counting from [from] to [to] inclusive, in steps of [step].
  ///
  /// Counts downward when [to] is below [from], which is what makes
  /// [countdown] a one-line call rather than a special case.
  static List<String> range(int from, int to, {int step = 1}) {
    assert(step > 0, 'step must be positive; pass to < from to count down');

    final List<String> items = <String>[];
    if (to >= from) {
      for (int n = from; n <= to; n += step) {
        items.add('$n');
      }
    } else {
      for (int n = from; n >= to; n -= step) {
        items.add('$n');
      }
    }
    return items;
  }

  /// 2, 4, 6, … up to and including [upTo].
  static List<String> evens(int upTo) => range(2, upTo, step: 2);

  /// 1, 3, 5, … up to and including [upTo].
  static List<String> odds(int upTo) => range(1, upTo, step: 2);

  /// [from] down to [to], e.g. 20 → 19 → 18 …
  static List<String> countdown({required int from, int to = 1}) =>
      range(from, to);

  /// The times table of [of]: `of`, `2 × of`, … [count] terms in all.
  static List<String> multiples({required int of, required int count}) =>
      <String>[for (int n = 1; n <= count; n++) '${of * n}'];
}
